=== tbuechner/export-analysis/package-thinned-out-schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="de" type="xs:string"/>
  <xs:element name="en" type="xs:string"/>
  <xs:simpleType name="EntityClassType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cf.cplace.platform.assets.group.Group"/>
      <xs:enumeration value="cf.cplace.platform.assets.group.Person"/>
      <xs:enumeration value="cf.cplace.platform.assets.file.Page"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="multiplicity">
    <xs:annotation>
      <xs:documentation>
        The 'multiplicity' element specifies the cardinality constraints for an attribute of the data model.
        It can optionally define constraints on the number of occurrences via the 'key' attribute.
        If the 'key' attribute is not set, the cardinality of the attribute is any number of values.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="key" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="anyNumber"/>
            <xs:enumeration value="exactlyOne"/>
            <xs:enumeration value="maximalOne"/>
            <xs:enumeration value="atLeastOne"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="de" minOccurs="0"/>
        <xs:element ref="en" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="localizedName">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="en"/>
        <xs:element ref="de"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="localizedShortName">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="en" minOccurs="0"/>
        <xs:element ref="de" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="shortHelp" type="xs:string"/>
  <xs:element name="stringConstraint">
  </xs:element>
  <xs:element name="language" type="xs:string"/>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="language" minOccurs="0"/>
        <xs:element ref="value" minOccurs="0"/>
        <xs:element ref="localizations" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="key" type="xs:string"/>
  <xs:element name="entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="key"/>
        <xs:element ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="localizations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="elements" type="xs:string"/>
  <xs:element name="element2icon">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="entry" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="element2localizedLabel">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="entry" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="textEnumerationConstraint">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="defaultValues" minOccurs="0"/>
        <xs:element ref="elements" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="element2icon"/>
        <xs:element ref="element2localizedLabel"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="defaultValues" type="xs:string"/>
  <xs:element name="typeNames" type="xs:string"/>
  <xs:element name="entityClass" type="EntityClassType">
    <xs:annotation>
      <xs:documentation>
        The 'entityClass' element specifies the class of the entity to which the reference points. It can have the following values:
        - 'cf.cplace.platform.assets.group.Group' if the target is a group,
        - 'cf.cplace.platform.assets.group.Person' if the target is a user,
        - 'cf.cplace.platform.assets.file.Page' otherwise.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="localizedInverseRoleName" type="xs:string"/>
  <xs:element name="sameWorkspace" type="xs:string"/>
  <xs:element name="isHierarchy" type="xs:string"/>
  <xs:element name="referenceConstraint">
    <xs:annotation>
      <xs:documentation>
        The 'referenceConstraint' element is used to define an attribute which is a reference attribute or relationship between entities in the data model.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element ref="defaultValues" minOccurs="0"/>
        <xs:element ref="typeNames" minOccurs="0"/>
        <xs:element ref="localizedInverseRoleName"/>
        <xs:element ref="sameWorkspace"/>
        <xs:element ref="isHierarchy"/>
        <xs:element ref="entityClass"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="specificity" type="xs:string"/>
  <xs:element name="dateFormat" type="xs:string"/>
  <xs:element name="dateConstraint">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="specificity"/>
        <xs:element ref="dateFormat"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="localizedNameSingular">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="en"/>
        <xs:element ref="de"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="localizedNamePlural">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="en" minOccurs="0"/>
        <xs:element ref="de" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iconName" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        'iconName' is the name of the icon that represents the type in the user interface. It is a Font Awesome icon name.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="attributes">
    <xs:complexType>
      <xs:all>
        <xs:element ref="name"/>
        <xs:element ref="localizedName"/>
        <xs:element ref="localizedShortName"/>
        <xs:element ref="shortHelp"/>
        <xs:element ref="stringConstraint" minOccurs="0"/>
        <xs:element ref="textEnumerationConstraint" minOccurs="0"/>
        <xs:element ref="referenceConstraint" minOccurs="0"/>
        <xs:element ref="dateConstraint" minOccurs="0"/>
        <xs:element ref="numberConstraint" minOccurs="0"/>
        <xs:element ref="richStringConstraint" minOccurs="0"/>
        <xs:element ref="multiplicity"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="precision" type="xs:byte"/>
  <xs:element name="localizedTextAfterSupplier" type="xs:string"/>
  <xs:element name="numberConstraint">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="precision"/>
        <xs:element ref="localizedTextAfterSupplier"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="richStringConstraint">
  </xs:element>
  <xs:element name="typeDef">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="localizedNameSingular"/>
        <xs:element ref="localizedNamePlural"/>
        <xs:element ref="iconName"/>
        <xs:element ref="attributes" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="page" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="name"/>
              <xs:element name="id" type="xs:string"/>
              <xs:element name="custom">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="type" type="xs:string"/>
                    <xs:element name="attributes">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="attribute" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="values">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="value" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="name"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="types">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typeDef" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="workspace">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="pages"/>
        <xs:element ref="types"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="slot">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="workspace"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="internalName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="shortname" type="xs:string"/>
  <xs:element name="slots">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="slot"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="package">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="shortname"/>
        <xs:element ref="slots"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="internalName"/>
      <xs:attribute type="xs:byte" name="version"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="solutionManagement">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="package"/>
      </xs:sequence>
      <xs:attribute type="xs:float" name="xmlVersion"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tbuechner/export-analysis/generated-pkgs/package-1/export.xml
<solutionManagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlVersion="1.8" xsi:noNamespaceSchemaLocation="../package-thinned-out-schema.xsd">
  <package internalName="cf.cplace.riskManagement" version="1">
    <name>
      <de>Risikomanagement-Anwendung</de>
      <en>Risk Management Application</en>
    </name>
    <shortname />
    <slots>
      <slot internalName="cf.cplace.riskManagement.risks">
        <name>
          <de>Risiken</de>
          <en>Risks</en>
        </name>
        <workspace>
          <name>RiskManagement</name>
          <types>
            <typeDef>
              <name>cf.cplace.riskManagement.risk</name>
              <localizedNameSingular>
                <en>Risk</en>
                <de>Risiko</de>
              </localizedNameSingular>
              <localizedNamePlural>
                <en>Risks</en>
                <de>Risiken</de>
              </localizedNamePlural>
              <iconName>fa-exclamation-triangle</iconName>
              <attributes>
                <name>cf.cplace.riskManagement.risk.name</name>
                <localizedName>
                  <en>Name</en>
                  <de>Name</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="stringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagement.risk.description</name>
                <localizedName>
                  <en>Description</en>
                  <de>Beschreibung</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="richStringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleRichStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagement.risk.probability</name>
                <localizedName>
                  <en>Probability</en>
                  <de>Wahrscheinlichkeit</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>2</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagement.risk.impact</name>
                <localizedName>
                  <en>Impact</en>
                  <de>Auswirkung</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>2</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagement.risk.level</name>
                <localizedName>
                  <en>Risk Level</en>
                  <de>Risikostufe</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>1</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagement.risk.mitigations</name>
                <localizedName>
                  <en>Mitigations</en>
                  <de>Minderungsmaßnahmen</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="referenceConstraint">
                  <typeNames>cf.cplace.riskManagement.mitigation</typeNames>
                  <entityClass>cf.cplace.platform.assets.file.Page</entityClass>
                  <localizedInverseRoleName />
                  <sameWorkspace>true</sameWorkspace>
                  <isHierarchy>false</isHierarchy>
                  <multiplicity />
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.MultiReferenceAttributeDef$MultiCustomReferenceAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <appliesTo>
                <key>page</key>
              </appliesTo>
              <localizedPageNamesMode>
                <key>none</key>
              </localizedPageNamesMode>
              <showNewButton>true</showNewButton>
            </typeDef>
            <typeDef>
              <name>cf.cplace.riskManagement.mitigation</name>
              <localizedNameSingular>
                <en>Mitigation</en>
                <de>Minderungsmaßnahme</de>
              </localizedNameSingular>
              <localizedNamePlural>
                <en>Mitigations</en>
                <de>Minderungsmaßnahmen</de>
              </localizedNamePlural>
              <iconName>fa-shield-alt</iconName>
              <attributes>
                <name>cf.cplace.riskManagement.mitigation.description</name>
                <localizedName>
                  <en>Description</en>
                  <de>Beschreibung</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="richStringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleRichStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagement.mitigation.cost</name>
                <localizedName>
                  <en>Cost</en>
                  <de>Kosten</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>2</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <appliesTo>
                <key>page</key>
              </appliesTo>
              <localizedPageNamesMode>
                <key>none</key>
              </localizedPageNamesMode>
              <showNewButton>true</showNewButton>
            </typeDef>
          </types>
          <apps>["cf.cplace.platform"]</apps>
          <rootPage>
            <page>
              <name>Root Page</name>
              <id>czpx9mj237dsnh8vg6h6yerzv</id>
              <custom>
                <type>default.page</type>
                <attributes />
              </custom>
              <widgetContainer>
                <widgetsLayout />
                <widgets />
              </widgetContainer>
            </page>
          </rootPage>
        </workspace>
      </slot>
    </slots>
    <cplaceRelease>24.1</cplaceRelease>
    <publishDate>2024-01-25T14:49:25.893+01:00</publishDate>
  </package>
  <maps />
</solutionManagement>

=== tbuechner/export-analysis/generated-pkgs/risk-mgmt/export.xml
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlVersion="1.0" internalName="cf.cplace.riskManagment" version="1" xsi:noNamespaceSchemaLocation="../package-thinned-out-schema.xsd">
  <package>
    <name>
      <de>Risikomanagement Anwendung</de>
      <en>Risk Management Application</en>
    </name>
    <slots>
      <slot internalName="cf.cplace.riskManagment.risks" workspaceName="Risk Management">
        <name>
          <de>Risiken</de>
          <en>Risks</en>
        </name>
        <workspace>
          <types>
            <typeDef>
              <name>cf.cplace.riskManagment.risk</name>
              <localizedNameSingular>
                <en>Risk</en>
                <de>Risiko</de>
              </localizedNameSingular>
              <localizedNamePlural>
                <en>Risks</en>
                <de>Risiken</de>
              </localizedNamePlural>
              <iconName>fa-exclamation-triangle</iconName>
              <attributes>
                <name>cf.cplace.riskManagment.risk.name</name>
                <localizedName>
                  <en>Name</en>
                  <de>Name</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="stringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagment.risk.description</name>
                <localizedName>
                  <en>Description</en>
                  <de>Beschreibung</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="richStringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleRichStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagment.risk.probability</name>
                <localizedName>
                  <en>Probability</en>
                  <de>Wahrscheinlichkeit</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>2</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagment.risk.impact</name>
                <localizedName>
                  <en>Impact</en>
                  <de>Auswirkung</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>2</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagment.risk.level</name>
                <localizedName>
                  <en>Risk Level</en>
                  <de>Risikostufe</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="stringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagment.risk.mitigations</name>
                <localizedName>
                  <en>Mitigations</en>
                  <de>Milderungsmaßnahmen</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="referenceConstraint">
                  <typeNames>cf.cplace.riskManagment.mitigation</typeNames>
                  <entityClass>cf.cplace.platform.assets.file.Page</entityClass>
                  <localizedInverseRoleName />
                  <sameWorkspace>true</sameWorkspace>
                  <isHierarchy>false</isHierarchy>
                  <multiplicity />
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.MultiReferenceAttributeDef$MultiCustomReferenceAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <appliesTo>
                <key>page</key>
              </appliesTo>
              <localizedPageNamesMode>
                <key>none</key>
              </localizedPageNamesMode>
              <showNewButton>true</showNewButton>
            </typeDef>
            <typeDef>
              <name>cf.cplace.riskManagment.mitigation</name>
              <localizedNameSingular>
                <en>Mitigation</en>
                <de>Milderungsmaßnahme</de>
              </localizedNameSingular>
              <localizedNamePlural>
                <en>Mitigations</en>
                <de>Milderungsmaßnahmen</de>
              </localizedNamePlural>
              <iconName>fa-shield-alt</iconName>
              <attributes>
                <name>cf.cplace.riskManagment.mitigation.description</name>
                <localizedName>
                  <en>Description</en>
                  <de>Beschreibung</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="richStringConstraint">
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleRichStringAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <attributes>
                <name>cf.cplace.riskManagment.mitigation.cost</name>
                <localizedName>
                  <en>Cost</en>
                  <de>Kosten</de>
                </localizedName>
                <localizedShortName />
                <shortHelp />
                <constraintFactory type="numberConstraint">
                  <precision>2</precision>
                  <localizedTextAfterSupplier />
                  <multiplicity>
                    <key>exactlyOne</key>
                  </multiplicity>
                  <attributeDefClass>cf.cplace.platform.assets.custom.def.SingleNumberAttributeDef</attributeDefClass>
                </constraintFactory>
              </attributes>
              <appliesTo>
                <key>page</key>
              </appliesTo>
              <localizedPageNamesMode>
                <key>none</key>
              </localizedPageNamesMode>
              <showNewButton>true</showNewButton>
            </typeDef>
          </types>
          <apps>["cf.cplace.platform"]</apps>
          <rootPage>
            <page>
              <name>Root Page</name>
              <id>bx19u8jtjdms36f1dv3d0612t</id>
              <custom>
                <type>default.page</type>
                <attributes />
              </custom>
              <widgetContainer>
                <widgetsLayout />
                <widgets />
              </widgetContainer>
            </page>
          </rootPage>
        </workspace>
      </slot>
    </slots>
    <cplaceRelease>24.1</cplaceRelease>
    <publishDate>2024-01-25T14:49:25.893+01:00</publishDate>
  </package>
  <maps />
</package>
